# Generated by Django 4.2.6 on 2023-11-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Meat & Poultry', 'Meat & Poultry')], default='Select a category', max_length=25),
        ),
    ]
